name: pan_seg_3d
channels:
- conda-forge
- robostack-staging
dependencies:
- python=3.9
- yaml-cpp
- pip
- numpy
- matplotlib
- scipy
- rospkg
- pybind11
- urdfdom
- ros-noetic-ros-base
- ros-noetic-tf2-msgs
- ros-noetic-rqt-plot
- ros-noetic-rqt-image-view
- ros-noetic-joint-state-publisher
- ros-noetic-cv-bridge
- ros-noetic-realsense2-camera
- catkin_tools
- pygame
- pip:
  - open3d
  - ultralytics
  - pymc
